# Generated by Django 4.1.7 on 2023-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajobaWebApp', '0004_alter_employee_ape_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(null=True, upload_to='empleados/'),
        ),
    ]
