# Generated by Django 4.1.7 on 2023-05-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MajobaWebApp', '0008_notification_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='count',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='receive',
            field=models.ManyToManyField(related_name='receiver_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
