# Generated by Django 4.1.7 on 2023-07-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajobaWebApp', '0011_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='obj_id',
        ),
    ]
