# Generated by Django 4.1.7 on 2023-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajobaWebApp', '0012_rename_type_notification_obj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
