# Generated by Django 4.1.7 on 2023-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajobaWebApp', '0015_alter_employee_img_alter_task_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
