# Generated by Django 4.2.3 on 2023-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajobaWebApp', '0017_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taker',
            field=models.IntegerField(default=0),
        ),
    ]
